const words = [
  "react", "redux", "hooks", "babel", "eslint", "vite", "node", "express", "mongo", "sqlite",
  "docker", "linux", "ubuntu", "arch", "zsh", "shell", "python", "numpy", "pandas", "flask",
  "django", "java", "spring", "kotlin", "swift", "xcode", "android", "ios", "flutter", "dart",
  "binary", "float", "int", "array", "object", "class", "method", "lambda", "async", "await",
  "promise", "closure", "scope", "loop", "while", "break", "continue", "switch", "case",
  "html", "css", "style", "tailwind", "sass", "less", "grid", "flex", "media", "query",
  "div", "span", "form", "input", "button", "submit", "select", "label", "table", "thead",
  "tbody", "tr", "td", "th", "svg", "canvas", "image", "video", "audio", "source",
  "script", "link", "meta", "title", "header", "footer", "section", "article", "aside", "main",
  "npm", "yarn", "pnpm", "package", "module", "export", "import", "require", "const",
  "let", "var", "function", "arrow", "statement", "block", "return", "yield", "this",
  "prototype", "oop", "fp", "state", "context", "props", "ref", "memo", "callback", "debounce",
  "throttle", "event", "listener", "target", "bubble", "capture", "prevent", "default", "stop", "ajax",
  "fetch", "axios", "get", "post", "put", "patch", "delete", "rest", "graphql", "api",
  "json", "xml", "http", "https", "url", "route", "path", "param", "hash", "cookie",
  "token", "jwt", "auth", "login", "logout", "signup", "register", "session", "cors", "cache",
  "code", "error", "try", "catch", "finally", "throw", "debug", "log", "trace", "warn",
  "info", "test", "unit", "jest", "mocha", "chai", "vitest", "cypress", "lint", "format",
  "prettier", "husky", "commit", "git", "push", "pull", "merge", "branch", "fork", "clone",
  "remote", "origin", "diff", "stash", "rebase", "tag", "version", "build", "run", "serve",
  "watch", "reload", "dev", "prod", "env", "config", "dotenv", "entry", "output", "loader",
  "plugin", "worker", "thread", "sync", "mutex", "lock", "race", "timeout", "interval",
  "settimeout", "setinterval", "callstack", "heap", "memory", "leak", "null", "undefined", "nan", "truthy",
  "falsy", "equals", "strict", "loose", "parse", "stringify", "number", "boolean", "string", "char",
  "regex", "pattern", "match", "search", "replace", "split", "slice", "splice", "push", "pop",
  "shift", "unshift", "map", "filter", "reduce", "find", "some", "every", "includes", "indexof",
  "concat", "join", "flat", "sort", "reverse", "keys", "values", "entries", "spread", "alias",
  "typescript", "interface", "enum", "union", "literal", "type", "cast", "assert", "guard", "extends",
  "generics", "partial", "readonly", "record", "pick", "omit", "unknown", "any", "never", "void"
];

export default words;
