const words = [
    "react", "redux", "hooks", "babel", "eslint", "vite", "node", "express", "mongo", "sqlite",
    "docker", "linux", "ubuntu", "arch", "zsh", "shell", "python", "numpy", "pandas", "flask",
    "django", "java", "spring", "kotlin", "swift", "xcode", "android", "ios", "flutter", "dart",
    "binary", "float", "int", "array", "object", "class", "method", "lambda", "async", "await",
    "promise", "closure", "scope", "loop", "while", "for", "break", "continue", "switch", "case",
    "html", "css", "style", "tailwind", "sass", "less", "grid", "flex", "media", "query",
    "div", "span", "form", "input", "button", "submit", "select", "label", "table", "thead",
    "tbody", "tr", "td", "th", "svg", "canvas", "image", "video", "audio", "source",
    "script", "link", "meta", "title", "header", "footer", "section", "article", "aside", "main",
    "npm", "yarn", "pnpm", "package", "json", "module", "export", "import", "require", "const",
    "let", "var", "function", "arrow", "expression", "statement", "block", "return", "yield", "this",
    "prototype", "constructor", "inheritance", "encapsulation", "polymorphism", "oop", "fp", "reactive", "state", "context",
    "props", "ref", "memo", "callback", "debounce", "throttle", "event", "listener", "target", "bubble",
    "capture", "prevent", "default", "stop", "propagation", "ajax", "fetch", "axios", "get", "post",
    "put", "patch", "delete", "rest", "graphql", "api", "json", "xml", "http", "https",
    "url", "route", "path", "param", "query", "hash", "cookie", "token", "jwt", "auth",
    "login", "logout", "signup", "register", "session", "cors", "cache", "header", "body", "status",
    "code", "error", "try", "catch", "finally", "throw", "debug", "log", "trace", "warn",
    "info", "test", "unit", "integration", "e2e", "jest", "mocha", "chai", "vitest", "cypress",
    "lint", "format", "prettier", "husky", "commit", "git", "push", "pull", "merge", "branch",
    "fork", "clone", "remote", "origin", "diff", "stash", "rebase", "checkout", "tag", "version",
    "build", "run", "serve", "watch", "hot", "reload", "dev", "prod", "env", "config",
    "dotenv", "tsconfig", "babelrc", "webpack", "rollup", "esbuild", "entry", "output", "loader", "plugin",
    "worker", "thread", "concurrent", "parallel", "sync", "mutex", "lock", "race", "timeout", "interval",
    "settimeout", "setinterval", "eventloop", "callstack", "heap", "garbage", "collector", "memory", "leak", "reference",
    "null", "undefined", "nan", "infinity", "truthy", "falsy", "equals", "strict", "loose", "compare",
    "parse", "stringify", "jsonparse", "jsonstringify", "number", "boolean", "string", "char", "regex", "pattern",
    "match", "search", "replace", "split", "slice", "splice", "push", "pop", "shift", "unshift",
    "map", "filter", "reduce", "find", "some", "every", "includes", "indexof", "concat", "join",
    "flat", "sort", "reverse", "keys", "values", "entries", "destructure", "spread", "rest", "alias",
    "typescript", "interface", "enum", "union", "literal", "type", "cast", "assert", "guard", "extends",
    "generics", "partial", "readonly", "record", "pick", "omit", "unknown", "any", "never", "void"
  ];
  
  export default words;
  